import turtle
t = turtle.Turtle()
jackie = turtle.Turtle()
jasmine = turtle.Turtle()
grace = turtle.Turtle()

jasmine.speed(0)
jackie.speed(0)
grace.speed(0)
t.speed(0)
#head
t.pensize(5)
t.fillcolor("#F3DBAC")
t.begin_fill()
t.circle(140)
t.penup()
t.end_fill()

#LeftEye
t.goto(80, 100)
t.pensize(2)
t.pendown()
t.fillcolor("white")
t.begin_fill()
t.circle(60)
t.penup()
t.end_fill()

#rightEye
t.goto(-80, 100)
t.pensize(2)
t.pendown()
t.fillcolor("white")
t.begin_fill()
t.circle(60)
t.penup()
t.end_fill()

#RightEye
t.goto(-72, 110)
t.pensize(2)
t.pencolor("#49B7CD")
t.pendown()
t.fillcolor("#49B7CD")
t.begin_fill()
t.circle(50)
t.penup()
t.end_fill()

#LeftEye
t.goto(88, 110)
t.pensize(2)
t.pencolor("#49B7CD")
t.pendown()
t.fillcolor("#49B7CD")
t.begin_fill()
t.circle(50)
t.penup()
t.end_fill()

#LeftEyeSmallBlack
t.goto(100, 120)
t.pensize(2)
t.pencolor("black")
t.pendown()
t.fillcolor("black")
t.begin_fill()
t.circle(40)
t.penup()
t.end_fill()

#RightEyeSmallBlack
t.goto(-61, 120)
t.pensize(2)
t.pencolor("black")
t.pendown()
t.fillcolor("black")
t.begin_fill()
t.circle(40)
t.penup()
t.end_fill()

#RightEyeSmallwhite
t.goto(-50, 160)
t.pensize(2)
t.pencolor("white")
t.pendown()
t.fillcolor("white")
t.begin_fill()
t.circle(15)
t.penup()
t.end_fill()

#LeftEyeSmallerwhite
t.goto(110, 160)
t.pensize(2)
t.pencolor("white")
t.pendown()
t.fillcolor("white")
t.begin_fill()
t.circle(15)
t.penup()
t.end_fill()

#mouth
t.goto(-30, 60)
t.pensize(5)
t.pencolor()
t.pencolor("black")
t.pendown()
t.rt(50)
t.circle(40, 100, 100)
t.penup()
#bangs

t.penup()
t.home()
t.goto(405,60)
t.pendown()
t.color("black")
t.begin_fill()
t.left(190)
t.forward(40)
t.right(5)
t.forward(60)
t.right(75)
t.forward(25)
t.left(145)
t.forward(25)
t.right(80)
t.forward(85)
t.right(120)
t.circle(-100,100)
t.end_fill()

# t.goto(-125, 200)
# t.pensize(5)
# t.pencolor("black")
# t.pendown()
# t.fillcolor("yellow")
# t.begin_fill()
# t.rt(70)
# t.circle(90, 100, 100)
# t.rt(155)
# t.circle(90, 100, 100)
# t.lt(93)
# t.circle(135, 130, 130)
# t.end_fill()
# t.penup()

#hair

t.penup()
t.home()
t.goto(-98, 245)
t.pendown()
t.color("black")
t.begin_fill()
t.left(20)
t.circle(70,100)

t.left(70)
t.forward(60)
t.right(5)
t.forward(60)
t.right(75)
t.forward(25)
t.left(145)
t.forward(25)

t.right(80)
t.forward(80)
t.right(5)
t.forward(38)
t.left(65)
t.circle(70,100)
t.left(-35)
t.circle(70,-56)
t.left(9)
t.circle(100,-179.7)
t.end_fill()


t.penup()
t.home()
t.goto(98, 245)
t.left(90)
t.pendown()
t.color("black")
t.begin_fill()
t.forward(18)
t.right(150)
t.forward(13)
t.left(140)
t.forward(20)
t.right(165)
t.forward(10)
t.right(5)
t.forward(14)
t.end_fill()
t.penup()


# t.goto(-98, 245)
# t.pensize(5)
# t.pencolor("black")
# t.pendown()
# t.fillcolor("yellow")
# t.begin_fill()
# t.rt(90)
# t.circle(70, 160, 160)
# t.lt(30)
# t.circle(71, 140, 140)
# t.end_fill()
# t.penup()

# t.goto(98, 245)
# t.pensize(5)
# t.pencolor("black")
# t.pendown()
# t.fillcolor("yellow")
# t.begin_fill()
# t.lt(130)
# t.circle(71, 140, 140)
# t.lt(35)
# t.circle(70, 150, 150)
# t.end_fill()
# t.penup()

#hairTie
# t.goto(95, 255)
# t.pensize(5)
# t.pencolor("#4983CD")
# t.pendown()
# t.fillcolor("#4983CD")
# t.begin_fill()
# t.circle(10)
# t.end_fill()
# t.penup()

# #hairTie
# t.goto(-105, 255)
# t.pensize(5)
# t.pencolor("#4983CD")
# t.pendown()
# t.fillcolor("#4983CD")
# t.begin_fill()
# t.circle(10)
# t.end_fill()
# t.penup()